# Generated by Django 2.0.5 on 2018-05-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=2)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('headers', models.CharField(blank=True, max_length=200, null=True)),
                ('response', models.CharField(max_length=200)),
                ('success_times', models.IntegerField(default=0)),
                ('failed_times', models.IntegerField(default=0)),
                ('last_fail', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
